### ISSUE TITLE
How to skip SocketError?

### ISSUE THREAD

**Issue by caecity43** [vifreefly/kimuraframework#11]
```
I, [2018-10-23T12:10:35.535202 #301]  INFO -- : Info: items: sent: 28, processed: 26
D, [2018-10-23T12:10:35.535471 #301] DEBUG -- : Browser: sleep 0.4 seconds before request...
I, [2018-10-23T12:10:35.935690 #301]  INFO -- : Browser: started get request to: https://www.video.com/?q=xxx&p=9
I, [2018-10-23T12:11:05.967685 #301]  INFO -- : Info: visits: requests: 38, responses: 37
I, [2018-10-23T12:11:05.967887 #301]  INFO -- : Browser: driver mechanize has been destroyed

Spider: stopped: {:spider_name=>"videos_spider", :status=>:failed, :error=>"#<SocketError: Failed to open TCP connection to www.video.com:443 (getaddrinfo: Name or service not known)>", :environment=>"production", :start_time=>2018-10-23 04:31:46 +0000, :stop_time=>2018-10-23 12:11:05 +0000, :running_time=>"7h, 39m", :visits=>{:requests=>38, :responses=>37}, :items=>{:sent=>28, :processed=>26}, :events=>{:requests_errors=>{}, :drop_items_errors=>{"#<Kimurai::Pipeline::DropItemError: Item download error.>"=>2}, :custom=>{}}}
```

I want to skip this error and keep spider to next page. 

My spider's config:

```ruby
@config = {
    skip_request_errors: [
      { error: RuntimeError, message: "404 => Net::HTTPNotFound" },
      { error: Net::HTTPNotFound, message: "404 => Net::HTTPNotFound" },
      { error: Down::ConnectionError, message: "Down::ConnectionError, Item Dropped." },
      { error: Net::OpenTimeout, message: "Net::OpenTimeout, Item Dropped." },
      { error: SocketError, message: "SocketError, Item Dropped." },
    ],
    before_request: {
      delay: 0.4
    }
  }
```

**Comment by vifreefly** [comment]
@caecity43 

Here is your error which you want to skip:
```
#<SocketError: Failed to open TCP connection to www.video.com:443 (getaddrinfo: Name or service not known)>
```
Where class of error is `SocketError` and message is `Failed to open TCP connection to www.video.com:443 (getaddrinfo: Name or service not known)`.

You config:
```
error: SocketError, message: "SocketError, Item Dropped." 
```
Like you see, there is no match. Correct will be: `error: SocketError, message: "Failed to open TCP connection to www.video.com"`. Or you can just provide error class as well, example: 

```
    skip_request_errors: [
      { error: RuntimeError, message: "404 => Net::HTTPNotFound" },
      { error: Net::HTTPNotFound, message: "404 => Net::HTTPNotFound" },
      { error: Down::ConnectionError, message: "Down::ConnectionError, Item Dropped." },
      { error: Net::OpenTimeout, message: "Net::OpenTimeout, Item Dropped." },
      SocketError
    ],
```
It will work as well.

**Comment by caecity43** [comment]
@vifreefly Thanks, I will try this. 👍

**Comment by caecity43** [comment]
```
Spider: stopped: {:spider_name=>"videos_spider", :status=>:failed, :error=>"#<RuntimeError: Received the following error for a GET request to https://www.videos.com/test'404 => Net::HTTPNotFound for https://www.videos.com/test -- unhandled response'>", :environment=>"production", :start_time=>2018-10-30 07:33:15 +0000, :stop_time=>2018-10-30 09:38:56 +0000, :running_time=>"2h, 5m", :visits=>{:requests=>27, :responses=>26}, :items=>{:sent=>13, :processed=>13}, :events=>{:requests_errors=>{}, :drop_items_errors=>{}, :custom=>{}}}
```

my config: 

```ruby
  @config = {
    #retry_request_errors: [Net::ReadTimeout],
    skip_request_errors: [
      { error: RuntimeError, message: "404 => Net::HTTPNotFound" },
      { error: Net::HTTPNotFound, message: "404 => Net::HTTPNotFound" },
      { error: Down::ConnectionError, message: "Down::ConnectionError, Item Dropped." },
      { error: Net::OpenTimeout, message: "Net::OpenTimeout, Item Dropped." },
      Net::HTTPNotFound,
      SocketError,
    ],
    before_request: {
      delay: 0.4
    }
  }
```

it not working.

**Comment by vifreefly** [comment]
@caecity43  which version of Kimurai do you use?

**Comment by vifreefly** [comment]
@caecity43, LGTM:

```
$ kimurai -v
1.2.0
```

```ruby
# example_spider.rb
require 'kimurai'
require 'net/http'

class ExampleSpider < Kimurai::Base
  @name = "example_spider"
  @engine = :mechanize
  @start_urls = ["https://www.videos.com/test"]
  @config = {
    skip_request_errors: [
      { error: RuntimeError, message: "404 => Net::HTTPNotFound" }
    ]
  }

  def parse(response, url:, data: {})
    logger.info response.title
  end
end

ExampleSpider.crawl!

```

```
$ ruby example_spider.rb

I, [2018-10-31 09:02:53 +0400#7185] [M: 46973272606200]  INFO -- example_spider: Spider: started: example_spider
D, [2018-10-31 09:02:54 +0400#7185] [M: 46973272606200] DEBUG -- example_spider: BrowserBuilder (mechanize): created browser instance
D, [2018-10-31 09:02:54 +0400#7185] [M: 46973272606200] DEBUG -- example_spider: BrowserBuilder (mechanize): enabled skip_request_errors
I, [2018-10-31 09:02:54 +0400#7185] [M: 46973272606200]  INFO -- example_spider: Browser: started get request to: https://www.videos.com/test
E, [2018-10-31 09:02:55 +0400#7185] [M: 46973272606200] ERROR -- example_spider: Browser: skip request error: #<RuntimeError: Received the following error for a GET request to https://www.videos.com/test: '404 => Net::HTTPNotFound for https://www.videos.com/test -- unhandled response'>, url: https://www.videos.com/test
I, [2018-10-31 09:02:55 +0400#7185] [M: 46973272606200]  INFO -- example_spider: Info: visits: requests: 1, responses: 0
I, [2018-10-31 09:02:55 +0400#7185] [M: 46973272606200]  INFO -- example_spider: Browser: driver mechanize has been destroyed
I, [2018-10-31 09:02:55 +0400#7185] [M: 46973272606200]  INFO -- example_spider: Spider: stopped: {:spider_name=>"example_spider", :status=>:completed, :error=>nil, :environment=>"development", :start_time=>2018-10-31 09:02:53 +0400, :stop_time=>2018-10-31 09:02:55 +0400, :running_time=>"1s", :visits=>{:requests=>1, :responses=>0}, :items=>{:sent=>0, :processed=>0}, :events=>{:requests_errors=>{"#<RuntimeError: Received the following error for a GET request to https://www.videos.com/test: '404 => Net::HTTPNotFound for https://www.videos.com/test -- unhandled response'>"=>1}, :drop_items_errors=>{}, :custom=>{}}}

```

**Comment by caecity43** [comment]
@vifreefly I use `1.2.0` too

**Comment by vifreefly** [comment]
@caecity43 

Ok, so my example spider above works for you? If not, provide minimal spider example which fails, so I will able to investigate the problem. Or I'll close this issue.

**Comment by caecity43** [comment]
@vifreefly 

the example is not the expected result.

```
[deploy@localhost spiders]$ ruby example_spider.rb
I, [2018-11-01 00:42:56 -0400#22641] [M: 47355832526360]  INFO -- example_spider: Spider: started: example_spider
D, [2018-11-01 00:42:57 -0400#22641] [M: 47355832526360] DEBUG -- example_spider: BrowserBuilder (mechanize): created browser instance
I, [2018-11-01 00:42:57 -0400#22641] [M: 47355832526360]  INFO -- example_spider: Browser: started get request to: https://www.videos.com/test
I, [2018-11-01 00:42:57 -0400#22641] [M: 47355832526360]  INFO -- example_spider: Info: visits: requests: 1, responses: 0
I, [2018-11-01 00:42:57 -0400#22641] [M: 47355832526360]  INFO -- example_spider: Browser: driver mechanize has been destroyed
F, [2018-11-01 00:42:57 -0400#22641] [M: 47355832526360] FATAL -- example_spider: Spider: stopped: {:spider_name=>"example_spider", :status=>:failed, :error=>"#<RuntimeError: Received the following error for a GET request to https://www.videos.com/test: '404 => Net::HTTPNotFound for https://www.videos.com/test -- unhandled response'>", :environment=>"development", :start_time=>2018-11-01 00:42:56 -0400, :stop_time=>2018-11-01 00:42:57 -0400, :running_time=>"0s", :visits=>{:requests=>1, :responses=>0}, :items=>{:sent=>0, :processed=>0}, :events=>{:requests_errors=>{}, :drop_items_errors=>{}, :custom=>{}}}
Traceback (most recent call last):
	13: from example_spider.rb:19:in `<main>'
	12: from /home/deploy/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/kimurai-1.1.0/lib/kimurai/base.rb:120:in `crawl!'
	11: from /home/deploy/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/kimurai-1.1.0/lib/kimurai/base.rb:120:in `each'
	10: from /home/deploy/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/kimurai-1.1.0/lib/kimurai/base.rb:121:in `block in crawl!'
	 9: from /home/deploy/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/kimurai-1.1.0/lib/kimurai/base.rb:194:in `request_to'
	 8: from /home/deploy/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/kimurai-1.1.0/lib/kimurai/capybara_ext/session.rb:20:in `visit'
	 7: from /home/deploy/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/capybara-3.7.2/lib/capybara/session.rb:262:in `visit'
	 6: from /home/deploy/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/capybara-3.7.2/lib/capybara/rack_test/driver.rb:44:in `visit'
	 5: from /home/deploy/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/capybara-3.7.2/lib/capybara/rack_test/browser.rb:23:in `visit'
	 4: from /home/deploy/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/capybara-3.7.2/lib/capybara/rack_test/browser.rb:42:in `process_and_follow_redirects'
	 3: from /home/deploy/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/capybara-3.7.2/lib/capybara/rack_test/browser.rb:75:in `process'
	 2: from /home/deploy/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/capybara-mechanize-1.11.0/lib/capybara/mechanize/browser.rb:47:in `block (2 levels) in <class:Browser>'
	 1: from /home/deploy/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/capybara-mechanize-1.11.0/lib/capybara/mechanize/browser.rb:119:in `process_remote_request'
/home/deploy/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/capybara-mechanize-1.11.0/lib/capybara/mechanize/browser.rb:141:in `rescue in process_remote_request': Received the following error for a GET request to https://www.videos.com/test: '404 => Net::HTTPNotFound for https://www.videos.com/test -- unhandled response' (RuntimeError)
```

**Comment by caecity43** [comment]
@vifreefly 

My bad, I still use 1.1.0.

it works after update to 1.2.0.
