### ISSUE TITLE
How to retry or skip Net::HTTP::Persistent::Error?

### ISSUE THREAD

**Issue by delavaler** [vifreefly/kimuraframework#39]
Hello
I sometimes get an error and want to skip it
```
Net::HTTP::Persistent::Error: too many connection resets (due to Net::ReadTimeout with #<TCPSocket:(closed)> - Net::ReadTimeout) after 0 requests on 47268817494080, last used 1585742984.5058694 seconds ago
/home/aleksandra/.rvm/gems/ruby-2.6.5/gems/rack-mini-profiler-2.0.1/lib/patches/net_patches.rb:9:in `block in request_with_mini_profiler'
/home/aleksandra/.rvm/gems/ruby-2.6.5/gems/rack-mini-profiler-2.0.1/lib/mini_profiler/profiling_methods.rb:39:in `step'
/home/aleksandra/.rvm/gems/ruby-2.6.5/gems/rack-mini-profiler-2.0.1/lib/patches/net_patches.rb:8:in `request_with_mini_profiler'
/home/aleksandra/.rvm/gems/ruby-2.6.5/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:55:in `block in request'
/home/aleksandra/.rvm/gems/ruby-2.6.5/gems/skylight-core-4.2.3/lib/skylight/core/fanout.rb:25:in `instrument'
/home/aleksandra/.rvm/gems/ruby-2.6.5/gems/skylight-core-4.2.3/lib/skylight/core/probes/net_http.rb:48:in `request'
/home/aleksandra/.rvm/gems/ruby-2.6.5/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:964:in `block in request'
/home/aleksandra/.rvm/gems/ruby-2.6.5/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:662:in `connection_for'
/home/aleksandra/.rvm/gems/ruby-2.6.5/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:958:in `request'
/home/aleksandra/.rvm/gems/ruby-2.6.5/gems/mechanize-2.7.6/lib/mechanize/http/agent.rb:280:in `fetch'
/home/aleksandra/.rvm/gems/ruby-2.6.5/gems/mechanize-2.7.6/lib/mechanize.rb:464:in `get'
/home/aleksandra/.rvm/gems/ruby-2.6.5/gems/capybara-mechanize-1.11.0/lib/capybara/mechanize/browser.rb:131:in `process_remote_request'
/home/aleksandra/.rvm/gems/ruby-2.6.5/gems/capybara-mechanize-1.11.0/lib/capybara/mechanize/browser.rb:47:in `block (2 levels) in <class:Browser>'
/home/aleksandra/.rvm/gems/ruby-2.6.5/gems/capybara-3.31.0/lib/capybara/rack_test/browser.rb:68:in `process'
/home/aleksandra/.rvm/gems/ruby-2.6.5/gems/capybara-3.31.0/lib/capybara/rack_test/browser.rb:43:in `process_and_follow_redirects'
/home/aleksandra/.rvm/gems/ruby-2.6.5/gems/capybara-3.31.0/lib/capybara/rack_test/browser.rb:23:in `visit'
/home/aleksandra/.rvm/gems/ruby-2.6.5/gems/capybara-3.31.0/lib/capybara/rack_test/driver.rb:45:in `visit'
/home/aleksandra/.rvm/gems/ruby-2.6.5/gems/capybara-3.31.0/lib/capybara/session.rb:278:in `visit'
/home/aleksandra/.rvm/gems/ruby-2.6.5/gems/kimurai-1.4.0/lib/kimurai/capybara_ext/session.rb:21:in `visit'
/home/aleksandra/.rvm/gems/ruby-2.6.5/gems/kimurai-1.4.0/lib/kimurai/base.rb:201:in `request_to'
/home/aleksandra/.rvm/gems/ruby-2.6.5/gems/kimurai-1.4.0/lib/kimurai/base.rb:162:in `parse!'
/home/aleksandra/Projects/hub/app/models/job_ad.rb:80:in `block in scrape_job_ads'
/home/aleksandra/Projects/hub/app/models/job_ad.rb:78:in `each'
/home/aleksandra/Projects/hub/app/models/job_ad.rb:78:in `scrape_job_ads'
/home/aleksandra/Projects/hub/lib/tasks/scheduler.rake:78:in `block (2 levels) in <main>'
/home/aleksandra/.rvm/gems/ruby-2.6.5/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/aleksandra/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `eval'
/home/aleksandra/.rvm/gems/ruby-2.6.5/bin/ruby_executable_hooks:24:in `<main>'
```
When added this error to the @config 
``` @config = {
    before_request: { delay: 120..180 },
    skip_request_errors: [{ error: Net::HTTP::Persistent::Error }],
    retry_request_errors: [
      { error: RuntimeError, message: '520', skip_on_failure: true }
    ]
  }```
got ```NameError: uninitialized constant Net::HTTP::Persistent```
Is it possible to skip this error and continue?

**Comment by namiwang** [comment]
Did you try to add `require 'net/http'`?

**Comment by delavaler** [comment]
> Did you try to add `require 'net/http'`?

Yes, it didn't help, if I understood correctly, this error from mechanize engine.

**Comment by delavaler** [comment]
Thanks, if add `require 'mechanize'` it works
